### ISSUE TITLE
Much console spam with sf build 668

### ISSUE THREAD

**Issue by mrcoffee1026** [J3fftw1/SoundMuffler#18]
I can probably disable this plugin temporarily... I don't know if it is what is causing the other issue but other addon related blocks on the same network as this device run for a few moments and then vanish.

https://pastebin.com/5CheELkm

**Comment by mrcoffee1026** [comment]
Has nothing to do with the disappearing machines, those seem to be directly related to a needed update for 668 as well, not to the soundmuffler addon, although this addon also needs updated for this build.

**Comment by J3fftw1** [comment]
is this still happening?

**Comment by mrcoffee1026** [comment]
No, now the only issue seems to be that it just doesn't work.  No errors, but sound plays full volume no matter what the device is set at.

**Comment by J3fftw1** [comment]
can you make a ticket about it

**Comment by J3fftw1** [comment]
on the new repo https://github.com/Slimefun-Addon-Community/SoundMuffler

**Comment by mrcoffee1026** [comment]
ok i've done that, thanks!
