### ISSUE TITLE
Error spamming the console

### ISSUE THREAD

**Issue by bobhenl** [J3fftw1/SoundMuffler#20]
Hi, I'm running the latest builds + soundmuffler 20 devbuild:
![image](https://user-images.githubusercontent.com/18662086/111072008-01ecd500-84d9-11eb-8f52-8516ce592cff.png)

And I'm getting these errors sometimes https://pastebin.com/H9mH2qDL

**Comment by J3fftw1** [comment]
Do you have via verson on your server?

**Comment by J3fftw1** [comment]
Also wronf issue tracker

**Comment by bobhenl** [comment]
Yes I have. and how do you mean wrong issue tracker?

**Comment by J3fftw1** [comment]
https://github.com/Slimefun-Addon-Community/SoundMuffler
