### ISSUE TITLE
SoundMuffler not muffling sounds.

### ISSUE THREAD

**Issue by Cyber-MC** [J3fftw1/SoundMuffler#7]
Slimefun + Addon Versions: https://gyazo.com/329c46c0e40ec141625f379d687ddeef

Server Version: 1.15.2
ProtocolLib Version: 4.5.0

Description of Issue: The addon doesn't muffle sounds whatsoever, whether it be a mob, a piston, a block breaking, or even a Jukebox. A video of this can be seen below: 

https://www.youtube.com/watch?v=mEYU7BojdoM

**Comment by J3fftw1** [comment]
yea i should have been more clear with this Remind me in the somewhere feature to show it somewhere

but the machine needs energy
and it still doesnt muffle every sound since i need to write a package to muffle all effects that produce sound

**Comment by Cyber-MC** [comment]
Ah, gotcha, power should do the trick then
