### ISSUE TITLE
The addon needs updating.

### ISSUE THREAD

**Issue by Cyber-MC** [J3fftw1/SoundMuffler#9]
Hello Panda, 

I'm creating this today to inform you that the addon needs to be updated sometime soon so that it will work with the latest DEV Builds of Slimefun-4. The reason for this is so that server owners, administrators, or co-owners like myself don't have to constantly be waiting for an update for an addon that seems like it is abandoned by this point though it has been almost a month now. I kindly hope that you take my request and put it to use, and I hope to speak with you again sometime soon.

Regards,

Cyber
WonderCraft Administration

**Comment by J3fftw1** [comment]
Hey cyber i fully understand where you comming from do you mind adding me on discord so i can give you a private statement

Panda.com#0806
